export const data = {
 nodes: {
 totalCount: 2989,
edges: [{
 id: '1aec1662-f95c-4f45-bdab-f673cfbda952',
title: 'Customer Service Asst Manager/ Sr.Executive, Executive',
organization: {
 popular_name: 'Logistic Integrators', name: 'Logistic Integrators India Private Limited', id: 'a2b12594-562e-4f3e-9f63-0c9a1e08ea37', __typename: 'Organization',
},
functional_area: { id: 38, name: 'Telesales / Telemarketing', __typename: 'ShortFunctionalArea' },
state: 'CLOSED',
stage: 'APPROVED',
pricing_plan_type: 'POSTPAID',
contract_type: 'PERMANENT',
client_approval_required: false,
is_screening_required: false,
is_resume_subscribed: false,
vacancies: 3,
locations: [],
expectation: { degree_requirements: null, work_exp_requirements: null, __typename: 'JobExpectation' },
offer: {
 salary_format: 'ANNUAL', min_offered_salary: 400000, max_offered_salary: 500000, __typename: 'JobOffer',
},
associated_cse: { user: { first_name: 'Pratik', last_name: 'Tawde', __typename: 'User' }, __typename: 'JobAssociatedCse' },
__typename: 'Job',
key: '1aec1662-f95c-4f45-bdab-f673cfbda952',
}, {
 id: '1af5c7dc-ec94-4d18-8905-f7a78ec8d380',
title: 'Field Sales Exectives',
organization: {
 popular_name: 'WTA Services', name: 'WTA Services Pvt Ltd', id: 'af5ddb05-6e8e-4d85-abe6-fbe60a7c9686', __typename: 'Organization',
},
functional_area: { id: 53, name: 'Sales / Business Development', __typename: 'ShortFunctionalArea' },
state: 'CLOSED',
stage: 'APPROVED',
pricing_plan_type: 'POSTPAID',
contract_type: 'PERMANENT',
client_approval_required: false,
is_screening_required: false,
is_resume_subscribed: false,
vacancies: 3,
locations: [],
expectation: { degree_requirements: null, work_exp_requirements: null, __typename: 'JobExpectation' },
offer: {
 salary_format: 'MONTHLY', min_offered_salary: 8000, max_offered_salary: 12000, __typename: 'JobOffer',
},
associated_cse: { user: { first_name: 'Payal', last_name: 'Nagpal', __typename: 'User' }, __typename: 'JobAssociatedCse' },
__typename: 'Job',
key: '1af5c7dc-ec94-4d18-8905-f7a78ec8d380',
}, {
 id: '1c3635ed-a82a-49b9-8e79-eb8bd049c9ed',
title: 'Xerox Machine Operator',
organization: {
 popular_name: 'Ganesh Book Depot', name: 'Ganesh Book Depot', id: '8be571f8-c909-44ea-8bc4-3e85337485d1', __typename: 'Organization',
},
functional_area: { id: 60, name: 'DTP Operator', __typename: 'ShortFunctionalArea' },
state: 'OPEN',
stage: 'REJECTED',
pricing_plan_type: 'POSTPAID',
contract_type: 'PERMANENT',
client_approval_required: false,
is_screening_required: false,
is_resume_subscribed: false,
vacancies: 1,
locations: [{ place: { city: 'Mumbai', locality: null, __typename: 'Place' }, __typename: 'JobLocationNew' }],
expectation: { degree_requirements: null, work_exp_requirements: null, __typename: 'JobExpectation' },
offer: {
 salary_format: 'MONTHLY', min_offered_salary: 10000, max_offered_salary: 12000, __typename: 'JobOffer',
},
associated_cse: { user: { first_name: 'Payal', last_name: 'Nagpal', __typename: 'User' }, __typename: 'JobAssociatedCse' },
__typename: 'Job',
key: '1c3635ed-a82a-49b9-8e79-eb8bd049c9ed',
}, {
 id: '1c530d31-6e09-4c30-bc2e-cad453c660d9',
title: 'Sales Executive-ICr',
organization: {
 popular_name: 'Nisha Tutorials', name: 'Nisha Tutorials', id: '87a569a6-684e-4e29-8b46-8e612125d703', __typename: 'Organization',
},
functional_area: { id: 64, name: 'Marketing Executive', __typename: 'ShortFunctionalArea' },
state: 'CLOSED',
stage: 'APPROVED',
pricing_plan_type: 'PREPAID',
contract_type: 'PERMANENT',
client_approval_required: false,
is_screening_required: false,
is_resume_subscribed: false,
vacancies: 1,
locations: [{ place: { city: 'Mumbai', locality: 'Malad East', __typename: 'Place' }, __typename: 'JobLocationNew' }],
expectation: { degree_requirements: null, work_exp_requirements: null, __typename: 'JobExpectation' },
offer: {
 salary_format: 'MONTHLY', min_offered_salary: 10000, max_offered_salary: 15000, __typename: 'JobOffer',
},
associated_cse: { user: { first_name: 'Zoyeb', last_name: 'Batliwala', __typename: 'User' }, __typename: 'JobAssociatedCse' },
__typename: 'Job',
key: '1c530d31-6e09-4c30-bc2e-cad453c660d9',
}, {
 id: '1c6917a0-b462-4eef-bbc9-e0a6c326d889',
title: 'xcvbnm,',
organization: {
 popular_name: 'Hardik sottany', name: 'Hardik sottany', id: '2f6dd45c-25bf-4777-a5d4-aa8d902bfd4c', __typename: 'Organization',
},
functional_area: { id: 61, name: 'Cashier', __typename: 'ShortFunctionalArea' },
state: 'OPEN',
stage: 'REJECTED',
pricing_plan_type: 'POSTPAID',
contract_type: 'PERMANENT',
client_approval_required: false,
is_screening_required: false,
is_resume_subscribed: false,
vacancies: 1,
locations: [{ place: { city: 'Mumbai', locality: 'Andheri East', __typename: 'Place' }, __typename: 'JobLocationNew' }],
expectation: { degree_requirements: null, work_exp_requirements: null, __typename: 'JobExpectation' },
offer: {
 salary_format: 'MONTHLY', min_offered_salary: 100000, max_offered_salary: 100000, __typename: 'JobOffer',
},
associated_cse: { user: { first_name: 'Payal', last_name: 'Nagpal', __typename: 'User' }, __typename: 'JobAssociatedCse' },
__typename: 'Job',
key: '1c6917a0-b462-4eef-bbc9-e0a6c326d889',
}, {
 id: '1ca0b648-2dfe-415b-adb2-8f9e5a1b29ae',
title: 'INBOUND AND OUTBOUND IN GHANSOLI',
organization: {
 popular_name: 'YASHICA RECRUITMENT SOLUTION', name: 'YASHICA RECRUITMENT SOLUTION', id: 'b4a7bcdf-ce47-41af-8f56-d4a015111512', __typename: 'Organization',
},
functional_area: { id: 38, name: 'Telesales / Telemarketing', __typename: 'ShortFunctionalArea' },
state: 'OPEN',
stage: 'REJECTED',
pricing_plan_type: 'POSTPAID',
contract_type: 'PERMANENT',
client_approval_required: false,
is_screening_required: false,
is_resume_subscribed: false,
vacancies: 10,
locations: [],
expectation: { degree_requirements: null, work_exp_requirements: null, __typename: 'JobExpectation' },
offer: {
 salary_format: 'MONTHLY', min_offered_salary: 8000, max_offered_salary: 9000, __typename: 'JobOffer',
},
associated_cse: { user: { first_name: 'Zoyeb', last_name: 'Batliwala', __typename: 'User' }, __typename: 'JobAssociatedCse' },
__typename: 'Job',
key: '1ca0b648-2dfe-415b-adb2-8f9e5a1b29ae',
}, {
 id: '1d5c7901-0644-47f8-aa50-54c857391911',
title: 'Sales Executive',
organization: {
 popular_name: 'Home Revise, Pune', name: 'Home Revise, Pune', id: '14e7a36c-80ec-45eb-a872-23b490de1485', __typename: 'Organization',
},
functional_area: { id: 53, name: 'Sales / Business Development', __typename: 'ShortFunctionalArea' },
state: 'OPEN',
stage: 'REJECTED',
pricing_plan_type: 'PREPAID',
contract_type: 'PERMANENT',
client_approval_required: false,
is_screening_required: false,
is_resume_subscribed: false,
vacancies: 5,
locations: [{ place: { city: 'Pune', locality: 'Sadashiv Peth', __typename: 'Place' }, __typename: 'JobLocationNew' }],
expectation: { degree_requirements: null, work_exp_requirements: { min_experience: 6, max_experience: 12, __typename: 'JobWorkExperienceRequirements' }, __typename: 'JobExpectation' },
offer: {
 salary_format: 'MONTHLY', min_offered_salary: 13000, max_offered_salary: 18000, __typename: 'JobOffer',
},
associated_cse: { user: { first_name: 'Mamta', last_name: 'Jadhav', __typename: 'User' }, __typename: 'JobAssociatedCse' },
__typename: 'Job',
key: '1d5c7901-0644-47f8-aa50-54c857391911',
}, {
 id: '1d6be626-e526-4dfa-8b47-58107573c82d',
title: 'Spark/Xpert/Champ/FC',
organization: {
 popular_name: 'Jubilant Foodworks Limited', name: 'Jubilant Foodworks Limited', id: 'ba39d1d2-e4a0-4b6a-aa90-497e4d6c7f80', __typename: 'Organization',
},
functional_area: { id: 43, name: 'Counter Sales', __typename: 'ShortFunctionalArea' },
state: 'CLOSED',
stage: 'APPROVED',
pricing_plan_type: 'POSTPAID',
contract_type: 'PERMANENT',
client_approval_required: false,
is_screening_required: false,
is_resume_subscribed: false,
vacancies: 7,
locations: [{ place: { city: 'Mumbai', locality: 'Andheri East', __typename: 'Place' }, __typename: 'JobLocationNew' }],
expectation: { degree_requirements: null, work_exp_requirements: null, __typename: 'JobExpectation' },
offer: {
 salary_format: 'MONTHLY', min_offered_salary: 8000, max_offered_salary: 8000, __typename: 'JobOffer',
},
associated_cse: { user: { first_name: 'Payal', last_name: 'Nagpal', __typename: 'User' }, __typename: 'JobAssociatedCse' },
__typename: 'Job',
key: '1d6be626-e526-4dfa-8b47-58107573c82d',
}, {
 id: '1e462757-9776-4564-bb29-0565f209f769',
title: 'Sales Executive',
organization: {
 popular_name: 'BRIQUE Technology Solutions and Consulting Pvt Ltd', name: 'BRIQUE Technology Solutions and Consulting Pvt Ltd', id: 'afab25ec-ce13-4421-bdaf-27996359a8a5', __typename: 'Organization',
},
functional_area: { id: 53, name: 'Sales / Business Development', __typename: 'ShortFunctionalArea' },
state: 'CLOSED',
stage: 'APPROVED',
pricing_plan_type: 'POSTPAID',
contract_type: 'PERMANENT',
client_approval_required: false,
is_screening_required: false,
is_resume_subscribed: true,
vacancies: 2,
locations: [{ place: { city: 'Mumbai', locality: 'Bhandup West', __typename: 'Place' }, __typename: 'JobLocationNew' }],
expectation: { degree_requirements: null, work_exp_requirements: null, __typename: 'JobExpectation' },
offer: {
 salary_format: 'MONTHLY', min_offered_salary: 15000, max_offered_salary: 25000, __typename: 'JobOffer',
},
associated_cse: { user: { first_name: 'Zoyeb', last_name: 'Batliwala', __typename: 'User' }, __typename: 'JobAssociatedCse' },
__typename: 'Job',
key: '1e462757-9776-4564-bb29-0565f209f769',
}, {
 id: '1e837ae7-04df-4a70-b472-89f238b132b8',
title: 'Executive Assistant ',
organization: {
 popular_name: 'Siddeshwar', name: 'Siddeshwar', id: 'b1bc8bd8-eef4-4658-bb93-032bbc4b17a2', __typename: 'Organization',
},
functional_area: { id: 42, name: 'Personal Assistant', __typename: 'ShortFunctionalArea' },
state: 'OPEN',
stage: 'UNAPPROVED',
pricing_plan_type: 'POSTPAID',
contract_type: 'PERMANENT',
client_approval_required: false,
is_screening_required: false,
is_resume_subscribed: false,
vacancies: 1,
locations: [{ place: { city: 'Pimpri-Chinchwad', locality: null, __typename: 'Place' }, __typename: 'JobLocationNew' }],
expectation: { degree_requirements: null, work_exp_requirements: null, __typename: 'JobExpectation' },
offer: {
 salary_format: 'MONTHLY', min_offered_salary: 15000, max_offered_salary: 50000, __typename: 'JobOffer',
},
associated_cse: { user: { first_name: 'Zoyeb', last_name: 'Batliwala', __typename: 'User' }, __typename: 'JobAssociatedCse' },
__typename: 'Job',
key: '1e837ae7-04df-4a70-b472-89f238b132b8',
}, {
 id: '1e8fedde-cccc-4bf9-b809-fe88e9079509',
title: 'Office Executive',
organization: {
 popular_name: 'Risemetric', name: 'Risemetric Technology LLP', id: '6241b59d-a6f2-4c42-86c4-f24940ed3486', __typename: 'Organization',
},
functional_area: { id: 32, name: 'Office Boy', __typename: 'ShortFunctionalArea' },
state: 'CLOSED',
stage: 'APPROVED',
pricing_plan_type: 'POSTPAID',
contract_type: 'PERMANENT',
client_approval_required: false,
is_screening_required: false,
is_resume_subscribed: false,
vacancies: 1,
locations: [],
expectation: { degree_requirements: null, work_exp_requirements: null, __typename: 'JobExpectation' },
offer: {
 salary_format: 'MONTHLY', min_offered_salary: 7500, max_offered_salary: 8500, __typename: 'JobOffer',
},
associated_cse: { user: { first_name: 'Zoyeb', last_name: 'Batliwala', __typename: 'User' }, __typename: 'JobAssociatedCse' },
__typename: 'Job',
key: '1e8fedde-cccc-4bf9-b809-fe88e9079509',
}, {
 id: '1eae9c1f-c449-4edb-8331-8e71b2632d34',
title: 'Asst. Manager',
organization: {
 popular_name: 'The Riot Room', name: 'The Riot Room', id: '7ef82ae3-afc1-499c-ba6b-ee0efef23bb8', __typename: 'Organization',
},
functional_area: { id: 26, name: 'Receptionist/Front Desk', __typename: 'ShortFunctionalArea' },
state: 'CLOSED',
stage: 'APPROVED',
pricing_plan_type: 'POSTPAID',
contract_type: 'PERMANENT',
client_approval_required: false,
is_screening_required: false,
is_resume_subscribed: false,
vacancies: 1,
locations: [{ place: { city: 'Thane', locality: 'Thane West', __typename: 'Place' }, __typename: 'JobLocationNew' }],
expectation: { degree_requirements: null, work_exp_requirements: null, __typename: 'JobExpectation' },
offer: {
 salary_format: 'MONTHLY', min_offered_salary: 11000, max_offered_salary: 13000, __typename: 'JobOffer',
},
associated_cse: { user: { first_name: 'Manisha', last_name: '2222', __typename: 'User' }, __typename: 'JobAssociatedCse' },
__typename: 'Job',
key: '1eae9c1f-c449-4edb-8331-8e71b2632d34',
}, {
 id: '1efc3d4f-3efc-400d-86d9-cdbd57a1e27d',
title: 'Account Executive',
organization: {
 popular_name: 'QuikWallet', name: 'LivQuik Technology India Pvt Ltd', id: 'ef10db52-3254-4c25-bf72-516084edf39f', __typename: 'Organization',
},
functional_area: { id: 33, name: 'Accountant', __typename: 'ShortFunctionalArea' },
state: 'CLOSED',
stage: 'APPROVED',
pricing_plan_type: 'POSTPAID',
contract_type: 'PERMANENT',
client_approval_required: false,
is_screening_required: false,
is_resume_subscribed: false,
vacancies: 1,
locations: [{ place: { city: 'Mumbai', locality: 'Powai', __typename: 'Place' }, __typename: 'JobLocationNew' }],
expectation: { degree_requirements: null, work_exp_requirements: null, __typename: 'JobExpectation' },
offer: {
 salary_format: 'MONTHLY', min_offered_salary: 22000, max_offered_salary: 27000, __typename: 'JobOffer',
},
associated_cse: { user: { first_name: 'Zoyeb', last_name: 'Batliwala', __typename: 'User' }, __typename: 'JobAssociatedCse' },
__typename: 'Job',
key: '1efc3d4f-3efc-400d-86d9-cdbd57a1e27d',
}, {
 id: '1ff79416-bbcd-4130-8ed4-c677473f7235',
title: 'Relationship Manager',
organization: {
 popular_name: 'HandyHome', name: 'Handy Home Solutions Pvt. Ltd.', id: '76559c8f-72c0-473c-8a5c-787fd9f1d3da', __typename: 'Organization',
},
functional_area: { id: 37, name: 'Customer Care', __typename: 'ShortFunctionalArea' },
state: 'CLOSED',
stage: 'APPROVED',
pricing_plan_type: 'POSTPAID',
contract_type: 'PERMANENT',
client_approval_required: false,
is_screening_required: false,
is_resume_subscribed: false,
vacancies: 1,
locations: [{ place: { city: 'Mumbai', locality: 'Powai', __typename: 'Place' }, __typename: 'JobLocationNew' }],
expectation: { degree_requirements: null, work_exp_requirements: null, __typename: 'JobExpectation' },
offer: {
 salary_format: 'MONTHLY', min_offered_salary: 12500, max_offered_salary: 17500, __typename: 'JobOffer',
},
associated_cse: { user: { first_name: 'Zoyeb', last_name: 'Batliwala', __typename: 'User' }, __typename: 'JobAssociatedCse' },
__typename: 'Job',
key: '1ff79416-bbcd-4130-8ed4-c677473f7235',
}, {
 id: '206d224b-6fd4-4b95-b21a-d724aec1ad73',
title: 'Support Executive',
organization: {
 popular_name: 'Vitruvian Technologies', name: 'Vitruvian Technologies Pvt. Ltd.', id: 'dc79ab35-a420-4bcd-ae99-5b0fcbe8ca5d', __typename: 'Organization',
},
functional_area: { id: 109, name: 'Software Developer', __typename: 'ShortFunctionalArea' },
state: 'CLOSED',
stage: 'APPROVED',
pricing_plan_type: 'POSTPAID',
contract_type: 'PERMANENT',
client_approval_required: false,
is_screening_required: false,
is_resume_subscribed: false,
vacancies: 4,
locations: [],
expectation: { degree_requirements: null, work_exp_requirements: null, __typename: 'JobExpectation' },
offer: {
 salary_format: 'ANNUAL', min_offered_salary: 300000, max_offered_salary: 400000, __typename: 'JobOffer',
},
associated_cse: { user: { first_name: 'Payal', last_name: 'Nagpal', __typename: 'User' }, __typename: 'JobAssociatedCse' },
__typename: 'Job',
key: '206d224b-6fd4-4b95-b21a-d724aec1ad73',
}, {
 id: '2190ac0a-a8d8-4168-8ef2-fcd291bb3d78',
title: 'Offset Estimator cum Planner',
organization: {
 popular_name: 'Face Marketing', name: 'Face Marketing', id: 'f50351ba-84d1-40f4-ba47-a195d089eb1c', __typename: 'Organization',
},
functional_area: { id: 60, name: 'DTP Operator', __typename: 'ShortFunctionalArea' },
state: 'PAUSED',
stage: 'APPROVED',
pricing_plan_type: 'PREPAID',
contract_type: 'PERMANENT',
client_approval_required: false,
is_screening_required: false,
is_resume_subscribed: true,
vacancies: 1,
locations: [{ place: { city: 'Mumbai', locality: 'Vikhroli West', __typename: 'Place' }, __typename: 'JobLocationNew' }],
expectation: { degree_requirements: null, work_exp_requirements: null, __typename: 'JobExpectation' },
offer: {
 salary_format: 'MONTHLY', min_offered_salary: 15000, max_offered_salary: 25000, __typename: 'JobOffer',
},
associated_cse: { user: { first_name: 'Snehal', last_name: 'Buchake', __typename: 'User' }, __typename: 'JobAssociatedCse' },
__typename: 'Job',
key: '2190ac0a-a8d8-4168-8ef2-fcd291bb3d78',
}, {
 id: '2192fbce-f1cc-4b89-a519-6b54dbcfee5e',
title: 'Receptionist',
organization: {
 popular_name: 'Gifting Ideas', name: 'Gifting Ideas Pvt. Ltd.', id: 'a2cfedcd-8f28-43b5-bd91-8e7ed5a0eb37', __typename: 'Organization',
},
functional_area: { id: 26, name: 'Receptionist/Front Desk', __typename: 'ShortFunctionalArea' },
state: 'CLOSED',
stage: 'APPROVED',
pricing_plan_type: 'POSTPAID',
contract_type: 'PERMANENT',
client_approval_required: false,
is_screening_required: false,
is_resume_subscribed: false,
vacancies: 1,
locations: [{ place: { city: 'Mumbai', locality: 'Lower Parel', __typename: 'Place' }, __typename: 'JobLocationNew' }],
expectation: { degree_requirements: null, work_exp_requirements: null, __typename: 'JobExpectation' },
offer: {
 salary_format: 'MONTHLY', min_offered_salary: 10000, max_offered_salary: 15000, __typename: 'JobOffer',
},
associated_cse: { user: { first_name: 'Zoyeb', last_name: 'Batliwala', __typename: 'User' }, __typename: 'JobAssociatedCse' },
__typename: 'Job',
key: '2192fbce-f1cc-4b89-a519-6b54dbcfee5e',
}, {
 id: '219f77de-8ee6-4360-8f04-d79b4db2fa54',
title: 'Customer Service Representative',
organization: {
 popular_name: 'CredR', name: 'Incredible Technologies Pvt Ltd', id: 'ed31d11f-0864-43f3-ad41-c0a65df94606', __typename: 'Organization',
},
functional_area: { id: 37, name: 'Customer Care', __typename: 'ShortFunctionalArea' },
state: 'CLOSED',
stage: 'APPROVED',
pricing_plan_type: 'POSTPAID',
contract_type: 'PERMANENT',
client_approval_required: false,
is_screening_required: false,
is_resume_subscribed: false,
vacancies: 2,
locations: [{ place: { city: 'Mumbai', locality: 'Ghatkopar East', __typename: 'Place' }, __typename: 'JobLocationNew' }, { place: { city: 'Mumbai', locality: 'Powai', __typename: 'Place' }, __typename: 'JobLocationNew' }],
expectation: { degree_requirements: null, work_exp_requirements: null, __typename: 'JobExpectation' },
offer: {
 salary_format: 'MONTHLY', min_offered_salary: 25000, max_offered_salary: 30000, __typename: 'JobOffer',
},
associated_cse: { user: { first_name: 'Payal', last_name: 'Nagpal', __typename: 'User' }, __typename: 'JobAssociatedCse' },
__typename: 'Job',
key: '219f77de-8ee6-4360-8f04-d79b4db2fa54',
}, {
 id: '21f6aee5-c536-4533-ab25-6c11651800f0',
title: 'Operations Executive- Snackible',
organization: {
 popular_name: 'Themis Consult', name: 'Themis Consult', id: '3da5d6a5-da48-4dd6-a62f-1a658eaf4634', __typename: 'Organization',
},
functional_area: { id: 51, name: 'Operations Executive', __typename: 'ShortFunctionalArea' },
state: 'CLOSED',
stage: 'APPROVED',
pricing_plan_type: 'POSTPAID',
contract_type: 'PERMANENT',
client_approval_required: false,
is_screening_required: false,
is_resume_subscribed: false,
vacancies: 5,
locations: [{ place: { city: 'Mumbai', locality: 'Ghatkopar West', __typename: 'Place' }, __typename: 'JobLocationNew' }],
expectation: { degree_requirements: null, work_exp_requirements: null, __typename: 'JobExpectation' },
offer: {
 salary_format: 'MONTHLY', min_offered_salary: 15000, max_offered_salary: 20000, __typename: 'JobOffer',
},
associated_cse: { user: { first_name: 'Purnima poornima', last_name: 'Katare Karte', __typename: 'User' }, __typename: 'JobAssociatedCse' },
__typename: 'Job',
key: '21f6aee5-c536-4533-ab25-6c11651800f0',
}, {
 id: '22d04735-dff1-4206-a142-0d79521f2faf',
title: 'Packing Executive',
organization: {
 popular_name: 'Grofers', name: 'Grofers India Pvt. Ltd. - TS', id: '9c5f681c-b0fb-4a6e-8c35-42f31f589efb', __typename: 'Organization',
},
functional_area: { id: 40, name: 'Packer', __typename: 'ShortFunctionalArea' },
state: 'CLOSED',
stage: 'APPROVED',
pricing_plan_type: 'TEMP_STAFFING',
contract_type: 'TEMPORARY',
client_approval_required: false,
is_screening_required: false,
is_resume_subscribed: false,
vacancies: 50,
locations: [{ place: { city: 'Thane', locality: null, __typename: 'Place' }, __typename: 'JobLocationNew' }, { place: { city: 'Mumbai', locality: 'Byculla', __typename: 'Place' }, __typename: 'JobLocationNew' }, { place: { city: 'Mumbai', locality: 'Mulund West', __typename: 'Place' }, __typename: 'JobLocationNew' }, { place: { city: 'Navi Mumbai', locality: 'Sanpada', __typename: 'Place' }, __typename: 'JobLocationNew' }, { place: { city: 'Mumbai', locality: 'Sion', __typename: 'Place' }, __typename: 'JobLocationNew' }, { place: { city: 'Thane', locality: 'Thane West', __typename: 'Place' }, __typename: 'JobLocationNew' }, { place: { city: 'Navi Mumbai', locality: 'Vashi', __typename: 'Place' }, __typename: 'JobLocationNew' }, { place: { city: 'Mumbai', locality: 'Worli', __typename: 'Place' }, __typename: 'JobLocationNew' }, { place: { city: 'Mumbai', locality: 'Juhu', __typename: 'Place' }, __typename: 'JobLocationNew' }, { place: { city: 'Mumbai', locality: 'Andheri East', __typename: 'Place' }, __typename: 'JobLocationNew' }],
expectation: { degree_requirements: null, work_exp_requirements: null, __typename: 'JobExpectation' },
offer: {
 salary_format: 'MONTHLY', min_offered_salary: 10000, max_offered_salary: 10000, __typename: 'JobOffer',
},
associated_cse: { user: { first_name: 'Rohan', last_name: 'Kikani', __typename: 'User' }, __typename: 'JobAssociatedCse' },
__typename: 'Job',
key: '22d04735-dff1-4206-a142-0d79521f2faf',
}],
pageInfo: {
 hasNextPage: true, totalPages: 150, pageNumber: 1, __typename: 'PageInfo',
},
__typename: 'NodeConnection',
},
};

export default data;
